<p><a href="#" class="btn">Button</a></p>
<p><a href="#" class="btn btn--alt">Alternate Button</a></p>
<p><a href="#" class="btn btn--cta">Call to action</a></p>
<p><a href="http://google.com" class="btn" disabled>Disabled Button</a></p>
<p><a href="#" class="btn btn--wide">Wide Button</a></p>
<p><button>Button Element</button></p>
<p><input type="submit" value="Submit Element" /></p>
<p><a href="#" class="btn btn--fixed-width">Fixed Width Button</a></p>
<p><a href="#" class="btn btn--highlight">Highlight Button</a></p>

<span class="sg-note">This is a different object to <code>.btn</code>. It's a simple link used within widgets and report areas.</span>
<p><a href="#" class="btn-text">Read ofcoms latest 2014 report</a></p>

<div class="band" style="background-color: #314f62;">
	<div class="wrapper">
		<a href="#" class="btn btn--transparent">Transparent Button</a>
	</div>
</div>

<div class="band">

	<span class="sg-note">If you have a couple of buttons in a row. Add the <code>.has-friend</code> class. It'll add <code>margin-right</code> to the element</span>
	<a href="#" class="btn has-friend">Has a friend</a><a href="#" class="btn btn--alt">Best Friend</a>
</div>

<div class="band--thick">

	<span class="sg-note">Some buttons are image based (like the Apple store ones). Here we use the <code>.btn-image</code> class. This class needs to be combined with the image class generated by grunticon</span>

	<a href="#" class="btn-image btn-image-app-store image-app-store / has-friend">Download on the App Store</a>
	<a href="" class="btn-image btn-image-play-store image-play-store">Download from the Google play store</a>

</div>